name: animated_container
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  smooth_page_indicator: ^2.0.1
  iconsax: ^0.0.8
  carousel_slider: ^5.1.1

  # State_Management
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/animations/
    - assets/images/
    - assets/icons/
    - assets/banners/

  fonts:
    - family: 'Nunito'
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800
